apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidfit-frontend
  namespace: aidfit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aidfit-frontend
  template:
    metadata:
      labels:
        app: aidfit-frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: aidfit-frontend
          image: ghcr.io/aid-fit/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
