apiVersion: v1
kind: Service
metadata:
  name: aidfit-frontend-svc
  namespace: aidfit
spec:
  selector:
    app: aidfit-frontend
  ports:
    - name: http
      port: 12571
      targetPort: 80
  type: LoadBalancer
